config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'boards#index'
  resources :boards
  resources :comments, only: %i[create destroy]
  resources :tags, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id             :integer          not null, primary key
#  body           :text             not null
#  comments_count :integer          default(0), not null
#  image          :string
#  title          :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer          not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#

class Board < ApplicationRecord
  belongs_to :owner, class_name: User, foreign_key: :user_id
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations, dependent: :delete_all
  mount_uploader :image, ImageUploader
  counter_culture :owner

  validates :title,
    presence: true,
    length: { maximum: 30 },
    uniqueness: { scope: :user_id }

  validates :body,
    presence: true,
    length: { maximum: 1000 }
end

app/models/board_tag_relation.rb
# == Schema Information
#
# Table name: board_tag_relations
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer          not null
#  tag_id     :integer          not null
#
# Indexes
#
#  index_board_tag_relations_on_board_id  (board_id)
#  index_board_tag_relations_on_tag_id    (tag_id)
#

class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#  index_comments_on_user_id   (user_id)
#

class Comment < ApplicationRecord
  belongs_to :content, class_name: Board, foreign_key: :board_id
  belongs_to :owner, class_name: User, foreign_key: :user_id
  validates :comment, presence: true, length: { maximum: 1000 }
  counter_culture :content
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_many :board_tag_relations, dependent: :delete_all
  has_many :boards, through: :board_tag_relations, dependent: :delete_all

  validates :name,
    presence: true,
    length: { maximum: 30 },
    uniqueness: { case_sensitive: false }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  avatar                 :string
#  boards_count           :integer          default(0), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           not null
#  point                  :integer          default(5), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_name                  (name) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  has_many :boards, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  validates :name,
    presence: true,
    length: { maximum: 30 },
    uniqueness: { case_sensitive: false }

  validates :point,
    presence: true,
    numericality: { only_integer: true,
    greater_than_or_equal_to: 0 }

  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  def lose_point!
    self.point -= 1
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[name email password password_confirmation remember_me avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    respond_to do |format|
      format.html do
        @boards = get_boards
        @boards = @boards.page(params[:page]).per(6).order('updated_at DESC')
      end
      format.csv do
        @boards = current_user.boards
        send_data render_to_string, filename: "current_user_boards.csv", type: :csv
      end
    end
  end

  def new
    @board = current_user.boards.new
  end

  def create
    Board.transaction do
      @board = current_user.boards.create!(board_params)
      current_user.lose_point!
    end
    flash[:notice] = "投稿しました。"
    redirect_to :root
  rescue => e
    flash[:alert] = @board.errors.full_messages
    render :new
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new(board_id: @board.id)
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      flash[:notice] = "編集しました。"
      redirect_to edit_board_path
    else
      flash[:alert] = @board.errors.full_messages
      render :edit
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
    flash[:notice] = "削除しました。"
    redirect_to :root
  end

  private

  def board_params
    params.require(:board).permit(:title, :body, :image, tag_ids: [])
  end

  def get_boards
    params[:tag_id].present? ? Tag.find(params[:tag_id]).boards.includes(:owner) : Board.includes(:owner).all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "コメントを投稿しました"
      redirect_to @comment.content
    else
      flash[:alert] = @comment.errors.full_messages
      redirect_back fallback_location: @comment.content
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    flash[:notice] = "コメントを削除しました"
    redirect_to @comment.content
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :board_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "タグを作成しました"
      redirect_to :root
    else
      flash[:alert] = @tag.errors.full_messages
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  APP_NAME = "RailsBoard".freeze

  def page_title
    base_title = APP_NAME
    return base_title if @title.blank?
    "#{base_title} | #{@title}"
  end

  def flash_message(message, klass)
    content_tag(:div, class: "alert alert-#{klass}") do
      concat content_tag(:a, 'x', class: 'close', data: { dismiss: 'alert' })
      concat raw(message)
    end
  end
end

app/views/boards/_board.html.haml
%tbody
  %tr
    %th= board.title
    %th= board.owner.name
    %th= board.created_at.to_s(:datetime)
    %th= board.updated_at.to_s(:datetime)
    %td= link_to '詳細', board, class: 'btn btn-outline-dark'
    - if board.owner == current_user
      %td= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete, data: { confirm: '削除してよろしいですか？' }
    - else
      %td

app/views/boards/_form.html.haml
= form_for @board do |f|
  .form-group
    = f.label :image, '画像'
    %br/
    = f.file_field :image
  .form-group
    = f.label :title, 'タイトル'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body, '本文'
    = f.text_area :body, class: 'form-control', rows: 10
  .form-group
    %span タグ
    = f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag|
      .form-check
        = tag.label class: 'form-check-label' do
          = tag.check_box class: 'form-check-input'
          = tag.text
  = f.submit '保存', class: 'btn btn-primary'

app/views/boards/_show_board.html.haml
.card
  .card-header
    = image_tag board.owner.avatar, class: "rounded-circle", style: "width: 25px;"
    %h4= board.title
    - board.tags.each do |tag|
      %span.badge.badge-primary= tag.name
  .card-body
    .py-3
      = image_tag board.image, class: "rounded-circle", style: "width: 80px;"
    %p.card-text= auto_link(simple_format(board.body), html: {target: '_blank'})
    %p.text-right.font-weight-bold.mr-10= board.owner.name

app/views/boards/edit.html.haml
.d-flex.align-items-center
  %h1 掲示板編集
  .ml-auto.boards__linkBox
    = link_to '一覧', root_path, class: 'btn btn-outline-dark'
    = link_to '詳細', @board, class: 'btn btn-outline-dark'
= render partial: "form", locals: { board: @board }

app/views/boards/index.html.haml
.row
  .col-md-2.col-12
    - if user_signed_in?
      .card.p-2
        = image_tag current_user.avatar, class: "card-img-top rounded-circle"
        .card-body
          %h4.card-title= "@#{current_user.name}"
          %p.card-text
            %span.text-secondary
            投稿数
            = current_user.boards_count
            %br
            %span.text-secondary
            = "#{current_user.created_at.to_s(:sign_up_time)}登録"
            %br
            %span.text-secondary
            = "ポイント #{current_user.point}"
            = link_to "CSV出力", root_path(format: :csv), class: "btn btn-primary"
  .col-md-10.col-12
    .d-flex.align-items-center
      %h1 掲示板一覧
      .ml-auto.boards__linkBox
        = form_tag boards_path, method: :get, class: 'boards__searchForm' do
          = select_tag :tag_id,                                                       |
            options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]), |
            {                                                                         |
              prompt: 'タグで絞り込み',                                                      |
              class: 'form-control boards__select',                                   |
              onchange: 'submit(this.form);'                                          |
            }                                                                |
        - if user_signed_in? && current_user.point > 0
          = link_to '新規作成',new_board_path, class: "btn btn-outline-dark"
        - if user_signed_in?
          = link_to 'タグ新規作成',new_tag_path, class: "btn btn-outline-dark"
    %table.table.table-hover.boards__table
      %thead.thead-dark
        %tr
          %th タイトル
          %th 作成者
          %th 作成日時
          %th 更新日時
          %th
          %th
      = render partial: "board", collection: @boards
    = paginate @boards

app/views/boards/new.html.haml
.d-flex.align-items-center
  %h1 掲示板作成
  .ml-auto.boards__linkBox
    = link_to '一覧', boards_path, class: 'btn btn-outline-dark'
= render partial: "form", locals: { board: @board }

app/views/boards/show.html.haml
.d-flex.align-items-center.mt-4.mb-4
  .ml-auto.boards__linkBox
    = link_to '一覧', boards_path, class: 'btn btn-outline-dark'
    - if @board.owner == current_user
      = link_to '編集', edit_board_path, class: 'btn btn-outline-dark'
= render partial: "show_board", locals: { board: @board }
.p-comment_list
  .p-comment_listTitle
    コメント(#{@board.comments_count})
    = render @board.comments
- if user_signed_in?
  = render partial: 'comments/form', locals: { comment: @comment }

app/views/comments/_comment.html.haml
.p-comment__item
  %p= auto_link(simple_format(comment.comment), html: {target: '_blank'})
  .p-comment__bottomLine
    %span= comment.owner.name
    %span= comment.created_at.to_s(:datetime)
    - if comment.owner == current_user
      %span= link_to '削除', comment, method: :delete, data: { confirm: '削除してよろしいですか？' }

app/views/comments/_form.html.haml
.p-comment__formBox
  %p.p-comment__formTitle コメント記入
  = form_for comment do |f|
    = f.hidden_field :board_id
    .form-group
      = f.label :comment, 'コメント'
      = f.text_area :comment, class: 'form-control', rows: 4
    = f.submit '送信', class: 'btn btn-primary'

app/views/layouts/_flash.html.haml
.py-4.px-0
  = flash_message(flash[:success], :success) if flash[:success]
  = flash_message(flash[:error], :danger) if flash[:error]
  = flash_message(flash[:alert], :warning) if flash[:alert]
  = flash_message(flash[:notice], :info) if flash[:notice]

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %small
      © 2018 
      = ApplicationHelper::APP_NAME

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.bg-dark
  .container
    = link_to ApplicationHelper::APP_NAME ,root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "プロフィール編集", edit_user_registration_path
          %li
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'アカウント登録', new_user_registration_path
          %li
            = link_to 'ログイン', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsBoards
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/flash'
      = yield
    = render 'layouts/footer'

app/views/tags/new.html.haml
.p-comment__formBox
  %p.p-comment__formTitle タグ名記入
  = form_for @tag do |f|
    .form-group
      = f.label :name, 'タグ'
      = f.text_area :name, class: 'form-control', rows: 4
    = f.submit '送信', class: 'btn btn-primary'